---
- hosts: localhost
  become: true
  tasks:
    - name: file creation 
      file:
        name: /tmp/a.txt
        state: touch
    - name: install
      apt:
        file:
          name: /tmp/a.txt
          state: directory
dsfasdfas
