---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: file creation 
      file:
        name: /tmp/prasanta12.txt
        state: touch
    - name: directory creation
      file:
        name: /tmp/demo12
        state: directory
    - name: httpd
      yum:
        name: httpd
        state: present
    - name: up
      service:
        name: httpd
        state: started
