---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: file creation 
      file:
        name: /tmp/prasanta.txt
        state: touch
    - name: directory creation
      file:
        name: /tmp/demo
        state: directory
